language: erlang
branches:
        only:
                - master
notifications:
        email: paulgray2@gmail.com
env:
        - R15B02
        - R15B01
        - R15B
        - R14B04
        - R14B03
        - R14B02
